name: ci

on:
  push:
  pull_request:
  schedule: [cron: "40 1 * * 0"]

jobs:

  test-release-build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - toolchain: "nightly-2025-01-01"

    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4

      - name: Setup | Toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "${{ matrix.toolchain }}"

      - name: Build | Release Mode
        run: cargo build --release

  unittest:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - toolchain: "nightly-2025-01-01"
            features: ""

    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4

      - name: Setup | Toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "${{ matrix.toolchain }}"

      - name: Test
        run: cargo test --features "${{ matrix.features }}"
        env:
          RUST_LOG: debug
          RUST_BACKTRACE: full

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2025-01-01
          components: rustfmt, clippy

      - name: Format
        run: cargo fmt --all -- --check

      - name: clippy
        shell: bash
        run: |
          cargo clippy --no-deps --workspace --all-targets -- -D warnings

      - name: Build-doc
        run: cargo doc --all --no-deps
        env:
          RUSTDOCFLAGS: "-D warnings"